main/urls.py
from django.urls import path, re_path
from . import views
from haystack.views import SearchView

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('play/<int:id>/', views.play, name='play'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path(r'add_videos/', views.add_video_path, name='add'),
    path('search/', SearchView()),
    path('delete/', views.delete_videos)
]

video/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models


# Create your models here.
class VideoInfo(models.Model):
    video_path = models.CharField(max_length=200, unique=True)
    video_name = models.CharField(max_length=50)

main/views.py
from django.shortcuts import render, redirect
from video.settings import BASE_DIR
import re
import os
from wsgiref.util import FileWrapper
from django.http import StreamingHttpResponse
from .tasks import generate_cover
from .models import VideoInfo
from django.core.paginator import Paginator
from django.conf import settings
import shutil


def add_video_path(request):
    if request.method == 'GET':
        return render(request, 'no_video.html', {'delete': True})
    path = request.POST.get('path')
    print(path)
    add_path(path)
    return render(request, 'alert.html', {'alert': '视频正在生成封面中，耐心等待'})


def add_path(video_path):
    # 如果该路径是文件夹，则递归调用
    if os.path.isdir(video_path):
        videos = os.listdir(video_path)
        for video in videos:
            add_path(os.path.join(video_path, video))
    else:
        file_path, file_ext = os.path.splitext(video_path)
        if file_ext.lower() in settings.VIDEOS_EXT:
            file_dir, file_name = os.path.split(file_path)
            try:
                video_info = VideoInfo()
                video_info.video_name = file_name
                video_info.video_path = video_path
                video_info.save()
                generate_cover.delay(video_path)
            except Exception:
                pass


def index(request):
    videos = VideoInfo.objects.order_by('id').all()
    if not videos:
        return redirect('main:add')
    paginator = Paginator(videos, 12)
    page_get = request.GET.get('p')
    if not page_get:
        page_get = 1
    videos_page = paginator.page(int(page_get))

    return render(request, 'index.html', {'files': videos_page, 'page': paginator})


def detail(request, id):
    return render(request, 'play.html', {'id': id})


def file_iterator(file_name, chunk_size=8192, offset=0, length=None):
    with open(file_name, "rb") as f:
        f.seek(offset, os.SEEK_SET)
        remaining = length
        while True:
            bytes_length = chunk_size if remaining is None else min(remaining, chunk_size)
            data = f.read(bytes_length)
            if not data:
                break
            if remaining:
                remaining -= len(data)
            yield data


def play(request, id):
    video = VideoInfo.objects.get(id=id)
    path = video.video_path
    """将视频文件以流媒体的方式响应"""
    range_header = request.META.get('HTTP_RANGE', '').strip()
    range_re = re.compile(r'bytes\s*=\s*(\d+)\s*-\s*(\d*)', re.I)
    range_match = range_re.match(range_header)
    size = os.path.getsize(path)
    # content_type, encoding = mimetypes.guess_type(path)
    content_type = 'application/octet-stream'
    if range_match:
        first_byte, last_byte = range_match.groups()
        first_byte = int(first_byte) if first_byte else 0
        last_byte = first_byte + 1024 * 1024 * 1  # 8M 每片,响应体最大体积
        if last_byte >= size:
            last_byte = size - 1
        length = last_byte - first_byte + 1
        resp = StreamingHttpResponse(file_iterator(path, offset=first_byte, length=length), status=206,
                                     content_type=content_type)
        resp['Content-Length'] = str(length)
        resp['Content-Range'] = 'bytes %s-%s/%s' % (first_byte, last_byte, size)
    else:
        # 不是以视频流方式的获取时，以生成器方式返回整个文件，节省内存
        resp = StreamingHttpResponse(FileWrapper(open(path, 'rb')), content_type='application/octet-stream')
        resp['Content-Length'] = str(size)
    resp['Accept-Ranges'] = 'bytes'
    return resp


def upload(request):
    if request.method == 'GET':
        return render(request, 'upload.html')
    files = request.FILES['file']
    file_name = files.name
    if not os.path.exists(os.path.join(BASE_DIR, 'uploads')):
        os.mkdir(os.path.join(BASE_DIR, 'uploads'))
    path = os.path.join(BASE_DIR, 'uploads', file_name)
    f = open(path, 'wb+')
    for file in files.chunks():
        f.write(file)
    f.close()
    add_path(path)
    generate_cover.delay(path)
    return render(request, 'alert.html', {'alert': '视频已添加，稍后就能展示'})


def delete_videos(request):
    shutil.rmtree(os.path.join(BASE_DIR, 'images'), ignore_errors=True)
    shutil.rmtree(os.path.join(BASE_DIR, 'uploads'), ignore_errors=True)
    VideoInfo.objects.all().delete()
    return render(request, 'alert.html', {'alert': '视频库已删除(包括已上传的视频)，请重新添加', 'delete': True})

templates/alert.html
{% extends 'base.html' %}
{% block body %}
    <div style="margin: auto;color:green;font-size: 30px">
        {{ alert }}
    </div>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="/static/images/favicon.ico">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body style="text-align: center;background-color: #2c2c2c">
{% block header %}
    <div>
        <nav class="navbar navbar-default">
            <div class="container-fluid ">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">BT天堂</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <form class="navbar-form navbar-right" action="/search" method="get">
                        <div class="form-group">
                            <input type="text" name="q" class="form-control" placeholder="搜索视频">
                        </div>
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        {% if not delete %}
                            <li>
                                <a href="javascript:if(confirm('确实要删除视频库中的记录？（原视频不会删除）')){location='/delete/'}">删除视频库</a>

                            </li>
                        {% endif %}
                        <li><a href="/upload">上传视频</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
{% endblock header %}
{% block body %}{% endblock body %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body %}
    <div style="margin: auto;height: 650px;width:850px;overflow:fragments;">
        {% for v in files %}
            <div style="margin-top: 10px;height: 200px;width:180px;display: inline-block;">
                <div style="height: 90%;width: 180px;">

                    <a href="{% url 'main:detail' v.id %}"><img src="static/images/{{ v.video_name }}.jpg"
                                                                alt="{{ v.video_name }}"
                                                                title="{{ v.video_name }}"/></a>
                </div>
                <div style="overflow: hidden;height: 10%;color:white">
                    <a href="{% url 'main:detail' v.id %}" style="text-decoration: none">{{ v.video_name }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if files.has_previous %}
                    <li>
                        <a href="?p={{ files.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    </li>
                {% endif %}
                <li><a>{{ files.number }}</a></li>
                {% if files.has_next %}
                    <li>
                        <a href="?p={{ files.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    </li>
                {% endif %}
                <li><a>共:{{ page.num_pages }}页</a></li>
            </ul>
        </nav>
    </div>
{% endblock body %}

templates/no_video.html
{% extends 'base.html' %}
{% block title %}

{% endblock title %}
{% block body %}
    <div style="margin: auto;color:green">
        <form action="/add_videos/" method="post">
            {% csrf_token %}
            <em>您还没有添加视频，输入视频所在的位置，提交后后台将逐个生成封面，请耐心等待</em>
            <br>
            视频路径
            <input name="path" type="text">
            <button>提交</button>
        </form>
    </div>
{% endblock body %}

templates/play.html
{% extends 'base.html' %}
{% block body %}
    <div style="margin:auto;height: 600px;width:1000px;">
        <video id="my-video" class="video-js" controls autoplay width="1000" height="600"
               data-setup="{}">
            <source src="/play/{{ id }}" type='video/mp4'>
            <p class="vjs-no-js">
                To view this video please enable JavaScript, and consider upgrading to a web browser that
                <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
            </p>
        </video>
    </div>
{% endblock body %}

templates/search/search.html
{% extends 'base.html' %}
{% block body %}
    <div style="margin: auto;height: 650px;width:850px;overflow:fragments;">
        {% if not page %}
            <div style="color:green;font-size:30px">
                <p>没有找到对应的视频</p>
            </div>
        {% endif %}
        {% for v in page %}
            <div style="margin-top: 10px;height: 200px;width:180px;display: inline-block;">
                <div style="height: 90%;width: 180px;">

                    <a href="{% url 'main:detail' v.object.id %}"><img
                            src="/static/images/{{ v.object.video_name }}.jpg"
                            alt="{{ v.object.video_name }}"/></a>
                </div>
                <div style="overflow: hidden;height: 10%;color:white">
                    <a href="{% url 'main:detail' v.object.id %}"
                       style="text-decoration: none">{{ v.object.video_name }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page.has_previous %}
                    <li>
                        <a href="/search/?q={{ query }}&page={{ page.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    </li>
                {% endif %}
                <li><a>{{ page.number }}</a></li>
                {% if page.has_next %}
                    <li>
                        <a href="/search/?q={{ query }}&page={{ page.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    </li>
                {% endif %}
                <li><a>共:{{ paginator.num_pages }}页</a></li>
            </ul>
        </nav>
    </div>
{% endblock body %}

templates/upload.html
{% extends 'base.html' %}
{% block body %}
    <div style="margin: auto;height: 300px;width: 400px;color:green">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file" style="margin: auto;display: inline-block"/>
            <input type="submit" value="上传文件" style="margin: auto;"/>
        </form>
    </div>
{% endblock body %}